function varargout = ThermaGUI(varargin)

gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
    'gui_Singleton',  gui_Singleton, ...
    'gui_OpeningFcn', @ThermaGUI_OpeningFcn, ...
    'gui_OutputFcn',  @ThermaGUI_OutputFcn, ...
    'gui_LayoutFcn',  [] , ...
    'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end

% --- Executes just before ThermaGUI is made visible.
function ThermaGUI_OpeningFcn(hObject, eventdata, handles, varargin)
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);

global cond_fig_limit comp_fig_limit
cond_fig_limit = 0;
comp_fig_limit = 0;

function varargout = ThermaGUI_OutputFcn(hObject, eventdata, handles)
varargout{1} = handles.output;


function cond_button_Callback(hObject, eventdata, handles)
global cond_fig_limit %Introduces limit which limits window to open once
if cond_fig_limit == 0 %If its not opened
    %Creates Conditions figure sets it to cond_figure
    cond_figure = figure(...
        'Position',[200,200,900,540],...
        'Resize','Off',...
        'MenuBar','none',...
        'Name','Conditions',...
        'tag','cond_fig',...
        'NumberTitle','off',...
        'CloseRequestFcn',@closereq);
    
    cond_intepara_pnl = uipanel(...
        'BorderType','etchedin',...
        'FontSize',10,...
        'FontWeight','bold',...
        'Units','pixels',...
        'Position',[20 305 250 205],...
        'Tag','cond_intepara_pnl',...
        'Title','Integration Parameter',...
        'TitlePosition','centertop');
    
    cond_intepara_elmtsz_txt
    
    cond_intepara_elmtsz_edit
    
    cond_intepara_timestp_txt
    
    cond_intepara_timestp_edit
    
    cond_intepara_dur_txt
    
    cond_intepara_dur_edit
    
    cond_intepara_outfreq_txt
    
    cond_intepara_elmt_txt
    
    cond_intepara_elmt_edit
    
    cond_intepara_timestps_txt
    
    cond_intepara_timestps_edit
    
    cond_objbond_pnl = uipanel(...
        'BorderType','etchedin',...
        'FontSize',10,...
        'FontWeight','bold',...
        'Units','pixels',...
        'Position',[290 60 600 460],...
        'Tag','cond_objbond_pnl',...
        'Title','Object Boundaries',...
    'TitlePosition','centertop');

    cond_objbond_topbond_txt
    
    cond_objbond_bttmbond_txt
    
    cond_topbond_expnl
    
    cond_topbond_inpnl
    
    cond_topbond_masstrans_txt
    
    cond_topbond_masstrans_edit1
    
    cond_topbond_masstrans_edit2
    
    cond_topbond_masstrans_edit3
    
    cond_topbond_masstrans_edit4
    
    cond_topbond_masstrans_edit5
    
    cond_topbond_addmt_pshbttn
    
    cond_topbond_remmt_pshbttn
    
    cond_topbond_outtemptimeprog_txt
    
    cond_topbond_outtemptimeprog_edit1
    
    cond_topbond_outtemptimeprog_edit2
    
    cond_topbond_convcoeff1_txt
    
    cond_topbond_convcoeff1_edit
    
    cond_topbond_exrad_txt
    
    cond_topbond_exrad_list
    
    cond_topbond_timeprog1_txt
    
    cond_topbond_timeprog1_edit1
    
    cond_topbond_timeprog1_edit2
    
    cond_topbond_timeprog1_edit3
    
    cond_topbond_timeprog2_txt
    
    cond_topbond_timeprog2_edit1
    
    cond_topbond_timeprog2_edit2
    
    cond_topbond_timeprog2_edit3
    
    cond_topbond_repeat_txt
    
    cond_topbond_repeat_list
    
    cond_topbond_absorpmode_txt
    
    cond_topbond_absorpmode_list
    
    cond_topbond_flame_txt
    
    cond_topbond_flame_list
    
    cond_topbond_ignmassflux_txt
    
    cond_topbond_ignmassflux_list
    
    cond_topbond_ignmassflux_edit
    
    cond_topbond_addimf_pshbttn
    
    cond_topbond_remimf_pshbttn
    
    cond_topbond_outtemp_txt
    
    cond_topbond_outtemp_edit
    
    cond_topbond_convcoeff2_txt
    
    cond_topbond_convcoeff2_edit
    
    cond_topbond_rad_txt
    
    cond_topbond_rad_edit
    
    cond_topbond_rad_txt
    
    cond_topbond_scroll_slider
    
    cond_bttmbond_expnl
    
    cond_bttmbond_inpnl
    
    cond_objstrct_pshbttn = uicontrol(...
        'Position',[50 125 200 50],...
        'String','Object Structure',...
        'Style','pushbutton',...
        'Tag','cond_objstrct_pshbttn',...
        'TooltipString','Default');
    
    cond_crte_pshbttn = uicontrol(...
        'Position',[700 25 150 30],...
        'String','Create Conditions',...
        'Style','pushbutton',...
        'Tag','cond_crte_pshbttn',...
        'TooltipString','Default');
    
    cond_selctcomp_pshbttn = uicontrol(...
        'Position',[500 25 150 30],...
        'String','Select Components file',...
        'Style','pushbutton',...
        'Tag','cond_selctcomp_pshbttn',...
        'TooltipString','Default',...
        'Visible','On');
    
    cond_reset_pshbttn = uicontrol(...
        'Position',[850 5 30 10],...
        'String','Reset',...
        'Style','pushbutton',...
        'Tag','cond_reset_pshbttn',...
        'TooltipString','Default');
    
    cond_fig_limit = 1; %sets limit to 1 which stops creation of figure
elseif cond_fig_limit == 1 %If it is opened
    cond_figure = findobj('Tag','cond_fig'); %set figure 'cond_fig' to cond_figure
    cond_figure.Visible = 'On'; %makes figure visible
    drawnow;
end

%This callback creates component figure when components button is clicked
function comp_button_Callback(hObject, eventdata, handles)
global comp_fig_limit %Introduces limit which limits window to open once
if comp_fig_limit == 0 %If its not opened
    comp_fig_limit = 1; %sets limit to 1 which stops creation of figure
    
    %enable for other design
    %Creates Components figure sets it to cond_figure
%     comp_figure = figure(...
%         'Position',[520 460 440 300],...
%         'Resize','Off',...
%         'MenuBar','none',...
%         'Name','Components',...
%         'tag','comp_fig',...
%         'CloseRequestFcn',@closereq);
    
    %Creates Components figure sets it to cond_figure
    comp_figure = figure(...
        'Position',[520 460 440 270],...
        'Resize','Off',...
        'MenuBar','none',...
        'Name','Components',...
        'tag','comp_fig',...
        'NumberTitle','off',...
        'CloseRequestFcn',@closereq);
    
    %Creates the list with the components
    comp_cmp_list = uicontrol(...
        'Position',[50 70 150 170],...
        'Style','listbox',...
        'String','ABS',...
        'Tag','comp_cmp_list');
    
    %Creates the text of intructions
    comp_help_txt = uicontrol(...
        'Position',[20 30 200 40],...
        'Style','text',...
        'String','HELP TEXT FILLER',...
        'Tag','comp_help_txt');
    
    %enable for other design
%     %Creates the list with the available components
%     comp_cmp_list = uicontrol(...
%         'Position',[50 200 150 60],...
%         'Style','listbox',...
%         'String','ABS',...
%         'Tag','comp_cmp_list');
%     
%     %Creates the list with the selected components
%     comp_xcmp_list = uicontrol(...
%         'Position',[50 100 150 60],...
%         'Style','listbox',...
%         'Tag','comp_xcmp_list',...
%         'Value',0);
%     
%     %Creates the button that removes components from the selected components
%     % list
%     comp_rem_cmp_list = uicontrol(...
%         'Position',[130 165 20 30],...
%         'Style','pushbutton',...
%         'String','-',...
%         'Tag','comp_cmp_list',...
%         'FontWeight','bold'...
%         'TooltipString','Default');
%     
%     %Create the button that adds the components to the selected components
%     % list
%     comp_add_cmp_list = uicontrol(...
%         'Position',[110 165 20 30],...
%         'Style','pushbutton',...
%         'String','+',...
%         'Tag','comp_cmp_list',...
%         'FontWeight','bold'...
%         'TooltipString','Default');

    %Creates the create button to create the components file
    comp_crte_pshbttn = uicontrol(...
        'Position',[140 10 160 30],...
        'Style','pushbutton',...
        'String','Create Components Files',...
        'Tag','comp_crte_pshbttn',...
        'TooltipString','Default');
    
    %Creates the Mixture Properties panel
    comp_mixprop_pnl = uipanel(...
        'Title','Mixture Properties',...
        'Units','pixels',...
        'Position',[240 80 200 160],...
        'FontWeight','bold',...
        'TitlePosition','centertop',...
        'BorderType','none');
    
%     %enable for other design
%     comp_mixprop_pnl = uipanel(...
%         'Title','Mixture Properties',...
%         'Units','pixels',...
%         'Position',[240 120 200 160],...
%         'FontWeight','bold',...
%         'TitlePosition','centertop',...
%         'BorderType','none');
    
    %Creates the text of Solid Swelling and edit text box inside the Mixture
    %Properties panel
    comp_mixprop_sswel_txt = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[0 120 70 15],...
        'Style','text',...
        'String','Solid Swelling',...
        'Tag','comp_mixprop_sswel_txt');
    comp_mixprop_sswel_edit = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[105 118 53 22],...
        'Style','edit',...
        'String','0',...
        'Tag','comp_mixprop_sswel_edit',...
        'TooltipString','Default');
    
    %Creates the text of Liquid Swelling and edit text box inside the Mixture
    %Properties panel
    comp_mixprop_lswel_txt = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[0 95 75 15],...
        'Style','text',...
        'String','Liquid Swelling',...
        'Tag','comp_mixprop_lswel_txt');
    comp_mixprop_lswel_edit = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[105 93 53 22],...
        'Style','edit',...
        'String','0',...
        'Tag','comp_mixprop_lswel_edit',...
        'TooltipString','Default');
    
    %Creates the text of Gas Swelling Limit and edit text box inside the
    %Mixutre Properties panel
    comp_mixprop_gswel_txt = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[0 70 90 15],...
        'Style','text',...
        'String','Gas Swelling Limit',...
        'Tag','comp_mixprop_gswel_txt');
    comp_mixprop_gswel_edit = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[105 68 53 22],...
        'Style','edit',...
        'String','1e-30',...
        'Tag','comp_mixprop_gswel_edit',...
        'TooltipString','Default');
    
    %Creates the text of Parallel Conductivity and edit text box inside the
    %Mixture Properties panel
    comp_mixprop_paracond_txt = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[0 45 100 15],...
        'Style','text',...
        'String','Parallel Conductivity',...
        'Tag','comp_mixprop_paracond_txt');
    comp_mixprop_paracond_edit = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[105 43 53 22],...
        'Style','edit',...
        'String','0.5',...
        'Tag','comp_mixprop_paracond_edit',...
        'TooltipString','Default');
    
    %Creates the text of Parallel Transport and edit text box inside the
    %Mixture Properties panel
    comp_mixprop_paratrans_txt = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[0 20 90 15],...
        'Style','text',...
        'String','Parallel Transport',...
        'Tag','comp_mixprop_paratrans_txt');
    comp_mixprop_paratrans_edit = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[105 18 53 22],...
        'Style','edit',...
        'String','0.5',...
        'Tag','comp_mixprop_gparatrans_edit',...
        'TooltipString','Default');
    
    %Creates the text of "Default Value" to indicate default Mixture Properties
    comp_mixprop_defvals_txt = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[40 0 90 15],...
        'Style','text',...
        'String','(Default Values)',...
        'Tag','comp_mixprop_defvals_txt',...
        'TooltipString','Default');
    
    %Creates the reset button to reset all settings in the Components figure
    comp_reset_pshbttn = uicontrol(...
        'Position',[400 10 35 15],...
        'Style','pushbutton',...
        'String','reset',...
        'Tag','comp_crte_pshbttn',...
        'TooltipString','Default');
    
    comp_help_pshbttn = uicontrol(...
        'Position',[400 10 35 15],...
        'Style','pushbutton',...
        'String','Help',...
        'Tag','comp_help_pshbttn',...
        'TooltipString','Default');
    
elseif comp_fig_limit == 1 %If it is opened
    comp_figure = findobj('Tag','comp_fig'); %set figure 'comp_fig' to comp_figure
    comp_figure.Visible = 'On'; %makes figure visible
    drawnow;
end

%This callback creates output figure when output button is clicked
function out_button_Callback(hObject, eventdata, handles)
global out_fig_limit %Introduces limit which limits window to open once
if out_fig_limit == 0 %If its not opened
    out_figure = figure(...
        'Position',[520 460 440 300],...
        'Resize','Off',... %Creates Output figure sets it to cond_figure
        'MenuBar','none',...
        'Name','Output',...
        'tag','out_fig',...
        'CloseRequestFcn',@closereq);
    out_fig_limit = 1; %sets limit to 1 which stops creation of figure
elseif out_fig_limit == 1 %If it is opened
    out_figure = findobj('Tag','comp_fig'); %set figure 'out_fig' to out_figure
    out_figure.Visible = 'On'; %makes figure visible
    drawnow;
end


function tk2d_button_Callback(hObject, eventdata, handles)

function closereq(src,callbackdata)
global cond_fig_limit comp_fig_limit out_fig_limit
fig_limit = [comp_fig_limit cond_fig_limit out_fig_limit];
idx = find(fig_limit==src);
% Close request function
% to display a question dialog box
selection = questdlg('Do you want to save?',...
    'Close Request Function',...
    'Yes','No','Yes');
switch selection,
    case 'Yes',
        %saves file
    case 'No'
        delete(gcf) %close figure without save
        fig_limit(idx)= 0; %reset limit to 0
        return
end

