function varargout = ThermaGUI(varargin)

gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
    'gui_Singleton',  gui_Singleton, ...
    'gui_OpeningFcn', @ThermaGUI_OpeningFcn, ...
    'gui_OutputFcn',  @ThermaGUI_OutputFcn, ...
    'gui_LayoutFcn',  [] , ...
    'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end

% --- Executes just before ThermaGUI is made visible.
function ThermaGUI_OpeningFcn(hObject, eventdata, handles, varargin)
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);

global cond_fig_limit comp_fig_limit
cond_fig_limit = 0;
comp_fig_limit = 0;

function varargout = ThermaGUI_OutputFcn(hObject, eventdata, handles)
varargout{1} = handles.output;

function cond_button_Callback(hObject, eventdata, handles)
global cond_fig_limit %Introduces limit which limits window to open once
if cond_fig_limit == 0 %If its not opened
    %Creates Conditions figure sets it to cond_figure
    cond_figure = figure(...
        'Position',[200,200,870,530],...
        'Resize','Off',...
        'MenuBar','none',...
        'Name','Conditions',...
        'tag','cond_fig',...
        'NumberTitle','off',...
        'CloseRequestFcn',@closereq);
    
%% Integration Parameters    
    cond_intepara_pnl = uipanel(...
        'Parent',cond_figure,...
        'BorderType','none',...
        'FontSize',10,...
        'FontWeight','bold',...
        'Units','pixels',...
        'Position',[20 335 200 175],...
        'Tag','cond_intepara_pnl',...
        'Title','Integration Parameter',...
        'TitlePosition','centertop');
    
    cond_intepara_elmtsz_txt = uicontrol(...
        'Parent',cond_intepara_pnl,...
        'Position',[20 130 70 15],...
        'Style','text',...
        'String','Element Size',...
        'Tag','cond_intepara_elmtsz_txt');
    
    cond_intepara_elmtsz_edit = uicontrol(...
        'Parent',cond_intepara_pnl,...
        'Position',[100 128 50 22],...
        'Style','edit',...
        'String','5e-5',...
        'Tag','cond_intepara_elmtsz_edit',...
        'TooltipString','Default');
    
    cond_intepara_timestp_txt = uicontrol(...
        'Parent',cond_intepara_pnl,...
        'Position',[35 110 55 15],...
        'Style','text',...
        'String','Time Step',...
        'Tag','cond_intepara_timestp_txt');
    
    cond_intepara_timestp_edit = uicontrol(...
        'Parent',cond_intepara_pnl,...
        'Position',[100 108 50 22],...
        'Style','edit',...
        'String','0.01',...
        'Tag','cond_intepara_timestp_edit',...
        'TooltipString','Default');
    
    cond_intepara_dur_txt = uicontrol(...
        'Parent',cond_intepara_pnl,...
        'Position',[40 90 50 15],...
        'Style','text',...
        'String','Duration',...
        'Tag','cond_intepara_dur_txt');
    
    cond_intepara_dur_edit = uicontrol(...
        'Parent',cond_intepara_pnl,...
        'Position',[100 88 50 22],...
        'Style','edit',...
        'String','600',...
        'Tag','cond_intepara_dur_edit',...
        'TooltipString','Default');
    
    cond_intepara_outfreq_txt = uicontrol(...
        'Parent',cond_intepara_pnl,...
        'Position',[65 55 100 15],...
        'Style','text',...
        'String','Output Frequency',...
        'Tag','cond_intepara_outfreq_txt');
    
    cond_intepara_elmt_txt = uicontrol(...
        'Parent',cond_intepara_pnl,...
        'Position',[40 30 50 15],...
        'Style','text',...
        'String','Elements',...
        'Tag','cond_intepara_elmt_txt');
    
    cond_intepara_elmt_edit = uicontrol(...
        'Parent',cond_intepara_pnl,...
        'Position',[100 28 50 22],...
        'Style','edit',...
        'String','20',...
        'Tag','cond_intepara_elmt_edit',...
        'TooltipString','Default');
    
    cond_intepara_timestps_txt = uicontrol(...
        'Parent',cond_intepara_pnl,...
        'Position',[30 10 60 15],...
        'Style','text',...
        'String','Time Steps',...
        'Tag','cond_intepara_timestps_txt');
    
    cond_intepara_timestps_edit = uicontrol(...
        'Parent',cond_intepara_pnl,...
        'Position',[100 8 50 22],...
        'Style','edit',...
        'String','100',...
        'Tag','cond_intepara_timestps_edit',...
        'TooltipString','Default');
%% Boundary
    cond_objbond_pnl = uipanel(...
        'BorderType','none',...
        'FontSize',10,...
        'FontWeight','bold',...
        'Units','pixels',...
        'Position',[230 50 600 460],...
        'Tag','cond_objbond_pnl',...
        'Title','Object Boundaries',...
    'TitlePosition','centertop');

    cond_objbond_topbond_txt = uicontrol(...
        'Parent',cond_objbond_pnl,...
        'Position',[80 420 100 15],...
        'Style','text',...
        'String','Top Boundary',...
        'Tag','cond_objbond_topbond_txt');
    
    cond_objbond_bttmbond_txt = uicontrol(...
        'Parent',cond_objbond_pnl,...
        'Position',[385 420 100 15],...
        'Style','text',...
        'String','Bottom Boundary',...
        'Tag','cond_objbond_bttmbond_txt');
%% Top Boundary

    cond_topbond_expnl = uipanel(...
        'Parent',cond_objbond_pnl,...
        'BorderType','none',...
        'Units','pixels',...
        'Position',[10 5 290 410],...
        'Tag','cond_topbond_expnl');
    
    cond_topbond_inpnl = uipanel(...
        'Parent',cond_topbond_expnl,...
        'BorderType','none',...
        'Units','pixels',...
        'Position',[0 0 275 410],...
        'Tag','cond_topbond_inpnl');
    
    cond_topbond_masstrans_txt = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[5 385 80 15],...
        'Style','text',...
        'String','Mass Transport',...
        'Tag','cond_topbond_masstrans_txt');
    
    cond_topbond_masstrans_menu = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[90 383 50 22],...
        'Style','popupmenu',...
        'String',{'YES';'NO'},...
        'Tag','cond_topbond_masstrans_menu',...
        'TooltipString','Default');
    
    cond_topbond_masstrans_menu2 = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[5 360 60 22],...
        'Style','popupmenu',...
        'String',' ',...
        'Tag','cond_topbond_masstrans_menu2',...
        'TooltipString','Default');
    
    cond_topbond_masstrans_menu3 = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[65 360 50 22],...
        'Style','popupmenu',...
        'String',{'EXP';'LIN'},...
        'Tag','cond_topbond_masstrans_menu3',...
        'TooltipString','Default');
    
    cond_topbond_masstrans_edit1 = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[115 360 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_topbond_masstrans_edit1',...
        'TooltipString','Default');
    
    cond_topbond_masstrans_edit2 = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[165 360 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_topbond_masstrans_edit2',...
        'TooltipString','Default');
    
    cond_topbond_addmt_pshbttn = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[220 359 20 24],...
        'Style','pushbutton',...
        'String','+',...
        'Tag','cond_topbond_addmt_pshbttn',...
        'FontWeight','bold',...
        'TooltipString','Default');
    
    cond_topbond_remmt_pshbttn = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[240 359 20 24],...
        'Style','pushbutton',...
        'String','-',...
        'Tag','cond_topbond_remmt_pshbttn',...
        'FontWeight','bold',...
        'TooltipString','Default');
    
    cond_topbond_outtemptimeprog_txt = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[5 320 140 15],...
        'Style','text',...
        'String','Outside Temp Time Program',...
        'Tag','cond_topbond_outtemptimeprog_txt');
    
    cond_topbond_outtemptimeprog_edit1 = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[150 318 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_topbond_outtemptimeprog_edit1',...
        'TooltipString','Default');
    
    cond_topbond_outtemptimeprog_edit2 = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[200 318 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_topbond_outtemptimeprog_edit2',...
        'TooltipString','Default');
    
    cond_topbond_convcoeff1_txt = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[5 295 105 15],...
        'Style','text',...
        'String','Convection Coeffient',...
        'Tag','cond_topbond_convcoeff1_txt');
    
    cond_topbond_convcoeff1_edit = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[115 293 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_topbond_convcoeff1_edit',...
        'TooltipString','Default');
    
    cond_topbond_exrad_txt = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[5 250 95 15],...
        'Style','text',...
        'String','External Radiation',...
        'Tag','cond_topbond_exrad_txt');
    
    cond_topbond_exrad_menu = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[105 248 50 22],...
        'Style','popupmenu',...
        'String',{'YES';'NO'},...
        'Tag','cond_topbond_exrad_menu',...
        'TooltipString','Default');
    
    cond_topbond_timeprog1_txt = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[5 225 80 15],...
        'Style','text',...
        'String','Time Program 1',...
        'Tag','cond_topbond_timeprog1_txt');
    
    cond_topbond_timeprog1_edit1 = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[90 223 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','',...
        'TooltipString','Default');
    
    cond_topbond_timeprog1_edit2 = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[140 223 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','',...
        'TooltipString','Default');
    
    cond_topbond_timeprog1_edit3 = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[190 223 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','',...
        'TooltipString','Default');
    
    cond_topbond_timeprog2_txt = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[5 200 80 15],...
        'Style','text',...
        'String','Time Program 2',...
        'Tag','cond_topbond_timeprog2_txt');
    
    cond_topbond_timeprog2_edit1 = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[90 198 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_topbond_timeprog2_edit1',...
        'TooltipString','Default');
    
    cond_topbond_timeprog2_edit2 = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[140 198 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_topbond_timeprog2_edit2',...
        'TooltipString','Default');
    
    cond_topbond_timeprog2_edit3 = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[190 198 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_topbond_timeprog2_edit3',...
        'TooltipString','Default');
    
    cond_topbond_repeat_txt = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[5 175 40 15],...
        'Style','text',...
        'String','Repeat',...
        'Tag','cond_topbond_repeat_txt');
    
    cond_topbond_repeat_menu = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[50 173 50 22],...
        'Style','popupmenu',...
        'String',{'YES';'NO'},...
        'Tag','cond_topbond_repeat_menu',...
        'TooltipString','Default');
    
    cond_topbond_absorpmode_txt = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[5 150 90 15],...
        'Style','text',...
        'String','Absorption Mode',...
        'Tag','cond_topbond_absorpmode_txt');
    
    cond_topbond_absorpmode_menu = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[100 148 55 22],...
        'Style','popupmenu',...
        'String',{'RAND';'MAX'},...
        'Tag','cond_topbond_absorpmode_menu',...
        'TooltipString','Default');
    
    cond_topbond_flame_txt = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[5 105 35 15],...
        'Style','text',...
        'String','Flame',...
        'Tag','cond_topbond_flame_txt');
    
    cond_topbond_flame_menu = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[40 103 50 22],...
        'Style','popupmenu',...
        'String',{'YES';'NO'},...
        'Tag','cond_topbond_flame_menu',...
        'TooltipString','Default');
    
    cond_topbond_ignmassflux_txt = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[5 80 105 15],...
        'Style','text',...
        'String','Ignition Mass Fluxes',...
        'Tag','cond_topbond_ignmassflux_txt');
    
    cond_topbond_ignmassflux_menu = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[110 78 60 22],...
        'Style','popupmenu',...
        'String',' ',...
        'Tag','cond_topbond_ignmassflux_menu',...
        'TooltipString','Default');
    
    cond_topbond_ignmassflux_edit = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[170 78 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_topbond_ignmassflux_edit',...
        'TooltipString','Default');
    
    cond_topbond_addimf_pshbttn = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[225 77 20 24],...
        'Style','pushbutton',...
        'String','+',...
        'Tag','cond_topbond_addimf_pshbttn',...
        'FontWeight','bold',...
        'TooltipString','Default');
    
    cond_topbond_remimf_pshbttn = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[245 77 20 24],...
        'Style','pushbutton',...
        'String','-',...
        'Tag','cond_topbond_remimf_pshbttn',...
        'FontWeight','bold',...
        'TooltipString','Default');
    
    cond_topbond_outtemp_txt = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[5 55 110 15],...
        'Style','text',...
        'String','Outside Temperature',...
        'Tag','cond_topbond_outtemp_txt');
    
    cond_topbond_outtemp_edit = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[120 53 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_topbond_outtemp_edit',...
        'TooltipString','Default');
    
    cond_topbond_convcoeff2_txt = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[5 30 120 15],...
        'Style','text',...
        'String','Convection Coefficient',...
        'Tag','cond_topbond_convcoeff2_txt');
    
    cond_topbond_convcoeff2_edit = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[125 28 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_topbond_convcoeff2_edit',...
        'TooltipString','Default');
    
    cond_topbond_rad_txt = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[5 5 50 15],...
        'Style','text',...
        'String','Radiation',...
        'Tag','cond_topbond_rad_txt');
    
    cond_topbond_rad_edit = uicontrol(...
        'Parent',cond_topbond_inpnl,...
        'Position',[60 3 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_topbond_rad_edit',...
        'TooltipString','Default');
 
    cond_topbond_scroll_slider = uicontrol(...
        'Parent',cond_topbond_expnl,...
        'Position',[275 0 15 410],...
        'Style','slider',...
        'Tag','cond_topbond_scroll_slider');
%% Bottom Boundary
    cond_bttmbond_expnl = uipanel(...
        'Parent',cond_objbond_pnl,...
        'BorderType','none',...
        'Units','pixels',...
        'Position',[310 5 290 410],...
        'Tag','cond_bttmbond_expnl');
    
    cond_bttmbond_inpnl = uipanel(...
        'Parent',cond_bttmbond_expnl,...
        'BorderType','none',...
        'Units','pixels',...
        'Position',[0 0 275 410],...
        'Tag','cond_bttmbond_inpnl');
     
    cond_bttmbond_masstrans_txt = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[5 385 80 15],...
        'Style','text',...
        'String','Mass Transport',...
        'Tag','cond_bttmbond_masstrans_txt');
    
    cond_bttmbond_masstrans_menu = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[90 383 50 22],...
        'Style','popupmenu',...
        'String',{'YES';'NO'},...
        'Tag','cond_bttmbond_masstrans_menu',...
        'TooltipString','Default');
    
    cond_bttmbond_masstrans_menu2 = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[5 360 60 22],...
        'Style','popupmenu',...
        'String',' ',...
        'Tag','cond_bttmbond_masstrans_menu2',...
        'TooltipString','Default');
    
    cond_bttmbond_masstrans_menu3 = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[65 360 50 22],...
        'Style','popupmenu',...
        'String',{'EXP';'LIN'},...
        'Tag','cond_bttmbond_masstrans_menu3',...
        'TooltipString','Default');
    
    cond_bttmbond_masstrans_edit1 = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[115 360 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_bttmbond_masstrans_edit1',...
        'TooltipString','Default');
    
    cond_bttmbond_masstrans_edit2 = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[165 360 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_bttmbond_masstrans_edit2',...
        'TooltipString','Default');
    
    cond_bttmbond_addmt_pshbttn = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[220 359 20 24],...
        'Style','pushbutton',...
        'String','+',...
        'Tag','cond_bttmbond_addmt_pshbttn',...
        'FontWeight','bold',...
        'TooltipString','Default');
    
    cond_bttmbond_remmt_pshbttn = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[240 359 20 24],...
        'Style','pushbutton',...
        'String','-',...
        'Tag','cond_bttmbond_remmt_pshbttn',...
        'FontWeight','bold',...
        'TooltipString','Default');
    
    cond_bttmbond_outtemptimeprog_txt = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[5 320 140 15],...
        'Style','text',...
        'String','Outside Temp Time Program',...
        'Tag','cond_bttmbond_outtemptimeprog_txt');
    
    cond_bttmbond_outtemptimeprog_edit1 = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[150 318 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_bttmbond_outtemptimeprog_edit1',...
        'TooltipString','Default');
    
    cond_bttmbond_outtemptimeprog_edit2 = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[200 318 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_bttmbond_outtemptimeprog_edit2',...
        'TooltipString','Default');
    
    cond_bttmbond_convcoeff1_txt = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[5 295 105 15],...
        'Style','text',...
        'String','Convection Coeffient',...
        'Tag','cond_bttmbond_convcoeff1_txt');
    
    cond_bttmbond_convcoeff1_edit = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[115 293 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_bttmbond_convcoeff1_edit',...
        'TooltipString','Default');
    
    cond_bttmbond_exrad_txt = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[5 250 95 15],...
        'Style','text',...
        'String','External Radiation',...
        'Tag','cond_bttmbond_exrad_txt');
    
    cond_bttmbond_exrad_menu = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[105 248 50 22],...
        'Style','popupmenu',...
        'String',{'YES';'NO'},...
        'Tag','cond_bttmbond_exrad_menu',...
        'TooltipString','Default');
    
    cond_bttmbond_timeprog1_txt = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[5 225 80 15],...
        'Style','text',...
        'String','Time Program 1',...
        'Tag','cond_bttmbond_timeprog1_txt');
    
    cond_bttmbond_timeprog1_edit1 = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[90 223 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','',...
        'TooltipString','Default');
    
    cond_bttmbond_timeprog1_edit2 = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[140 223 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','',...
        'TooltipString','Default');
    
    cond_bttmbond_timeprog1_edit3 = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[190 223 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','',...
        'TooltipString','Default');
    
    cond_bttmbond_timeprog2_txt = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[5 200 80 15],...
        'Style','text',...
        'String','Time Program 2',...
        'Tag','cond_bttmbond_timeprog2_txt');
    
    cond_bttmbond_timeprog2_edit1 = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[90 198 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_bttmbond_timeprog2_edit1',...
        'TooltipString','Default');
    
    cond_bttmbond_timeprog2_edit2 = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[140 198 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_bttmbond_timeprog2_edit2',...
        'TooltipString','Default');
    
    cond_bttmbond_timeprog2_edit3 = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[190 198 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_bttmbond_timeprog2_edit3',...
        'TooltipString','Default');
    
    cond_bttmbond_repeat_txt = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[5 175 40 15],...
        'Style','text',...
        'String','Repeat',...
        'Tag','cond_bttmbond_repeat_txt');
    
    cond_bttmbond_repeat_menu = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[50 173 50 22],...
        'Style','popupmenu',...
        'String',{'YES';'NO'},...
        'Tag','cond_bttmbond_repeat_menu',...
        'TooltipString','Default');
    
    cond_bttmbond_absorpmode_txt = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[5 150 90 15],...
        'Style','text',...
        'String','Absorption Mode',...
        'Tag','cond_bttmbond_absorpmode_txt');
    
    cond_bttmbond_absorpmode_menu = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[100 148 55 22],...
        'Style','popupmenu',...
        'String',{'RAND';'MAX'},...
        'Tag','cond_bttmbond_absorpmode_menu',...
        'TooltipString','Default');
    
    cond_bttmbond_flame_txt = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[5 105 35 15],...
        'Style','text',...
        'String','Flame',...
        'Tag','cond_bttmbond_flame_txt');
    
    cond_bttmbond_flame_menu = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[40 103 50 22],...
        'Style','popupmenu',...
        'String',{'YES';'NO'},...
        'Tag','cond_bttmbond_flame_menu',...
        'TooltipString','Default');
    
    cond_bttmbond_ignmassflux_txt = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[5 80 105 15],...
        'Style','text',...
        'String','Ignition Mass Fluxes',...
        'Tag','cond_bttmbond_ignmassflux_txt');
    
    cond_bttmbond_ignmassflux_menu = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[110 78 60 22],...
        'Style','popupmenu',...
        'String',' ',...
        'Tag','cond_bttmbond_ignmassflux_menu',...
        'TooltipString','Default');
    
    cond_bttmbond_ignmassflux_edit = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[170 78 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_bttmbond_ignmassflux_edit',...
        'TooltipString','Default');
    
    cond_bttmbond_addimf_pshbttn = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[225 77 20 24],...
        'Style','pushbutton',...
        'String','+',...
        'Tag','cond_bttmbond_addimf_pshbttn',...
        'FontWeight','bold',...
        'TooltipString','Default');
    
    cond_bttmbond_remimf_pshbttn = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[245 77 20 24],...
        'Style','pushbutton',...
        'String','-',...
        'Tag','cond_bttmbond_remimf_pshbttn',...
        'FontWeight','bold',...
        'TooltipString','Default');
    
    cond_bttmbond_outtemp_txt = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[5 55 110 15],...
        'Style','text',...
        'String','Outside Temperature',...
        'Tag','cond_bttmbond_outtemp_txt');
    
    cond_bttmbond_outtemp_edit = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[120 53 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_bttmbond_outtemp_edit',...
        'TooltipString','Default');
    
    cond_bttmbond_convcoeff2_txt = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[5 30 120 15],...
        'Style','text',...
        'String','Convection Coefficient',...
        'Tag','cond_bttmbond_convcoeff2_txt');
    
    cond_bttmbond_convcoeff2_edit = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[125 28 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_bttmbond_convcoeff2_edit',...
        'TooltipString','Default');
    
    cond_bttmbond_rad_txt = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[5 5 50 15],...
        'Style','text',...
        'String','Radiation',...
        'Tag','cond_bttmbond_rad_txt');
    
    cond_bttmbond_rad_edit = uicontrol(...
        'Parent',cond_bttmbond_inpnl,...
        'Position',[60 3 50 22],...
        'Style','edit',...
        'String',' ',...
        'Tag','cond_bttmbond_rad_edit',...
        'TooltipString','Default');
 
    cond_bttmbond_scroll_slider = uicontrol(...
        'Parent',cond_bttmbond_expnl,...
        'Position',[275 0 15 410],...
        'Style','slider',...
        'Tag','cond_bttmbond_scroll_slider');
%% Buttons
    cond_objstrct_pshbttn = uicontrol(...
        'Position',[20 140 200 50],...
        'String','Object Structure',...
        'Style','pushbutton',...
        'Tag','cond_objstrct_pshbttn',...
        'Callback',@cond_objstrct_pshbttn_callback,...
        'TooltipString','Default');
    
    cond_crte_pshbttn = uicontrol(...
        'Position',[680 15 150 30],...
        'String','Create Conditions',...
        'Style','pushbutton',...
        'Tag','cond_crte_pshbttn',...        
        'TooltipString','Default');
    
    cond_selctcomp_pshbttn = uicontrol(...
        'Position',[500 15 150 30],...
        'String','Select Components file',...
        'Style','pushbutton',...
        'Tag','cond_selctcomp_pshbttn',...
        'TooltipString','Default',...
        'Visible','On');
    
    cond_reset_pshbttn = uicontrol(...
        'Position',[5 5 30 10],...
        'String','Reset',...
        'Style','pushbutton',...
        'Tag','cond_reset_pshbttn',...
        'TooltipString','Default');
    
    cond_help_pshbttn = uicontrol(...
        'Position',[50 5 30 10],...
        'String','Help',...
        'Style','pushbutton',...
        'Tag','cond_help_pshbttn',...
        'TooltipString','Default');
    
    cond_fig_limit = 1; %sets limit to 1 which stops creation of figure
elseif cond_fig_limit == 1 %If it is opened
    cond_figure = findobj('Tag','cond_fig'); %set figure 'cond_fig' to cond_figure
    cond_figure.Visible = 'On'; %makes figure visible
    drawnow;
end

function cond_objstrct_pshbttn_callback(hObject, eventdata, handles)
global objstruct_figure objstruct_layer_pnl...
objstruct_title_pnl objstruct_title_txt...
objstruct_addlayer_pshbttn objstruct_remlayer_pshbttn...
objstruct_crteobjstruct_pshbttn objstruct_scroll_slider

objstruct_figure = figure(...
    'Position',[680,280,270,170],...
    'Resize','Off',...
    'MenuBar','none',...
    'Name','Object Structure',...
    'tag','objstruct_figure',...
    'Visible','on');
    
objstruct_layer_pnl = uipanel(...
    'Parent',objstruct_figure,...
    'Tag','objstruct_layer_pnl',...
    'Units','pixels',...
    'Position',[0 0 255 150],...
    'BorderType','none');

objstruct_title_pnl = uipanel(...
    'Parent',objstruct_figure,...
    'Tag','objstruct_title_pnl',...
    'Units','pixels',...
    'Position',[0 150 270 25],...
    'BorderType','none');

objstruct_title_txt = uicontrol(...
    'Parent',objstruct_title_pnl,...
    'Style','text',...
    'HorizontalAlignment','center',...
    'String','Object Structure',...
    'FontSize',15,...
    'FontWeight','bold',...
    'Units','pixels',...
    'Tag','objstruct_title_txt',...
    'Position',[60 0 185 25]);

objstruct_addlayer_txt = uicontrol(...
    'Parent',objstruct_layer_pnl,...
    'Style','text',...
    'Tag','objstruct_addlayer_txt',...
    'String','Add new layer',...
    'FontSize',10,...
    'Units','pixels',...
    'Position',[50 85 100 15]);

objstruct_addlayer_pshbttn = uicontrol(...
    'Parent',objstruct_layer_pnl,...
    'Style','pushbutton',...
    'String','+',...
    'Units','pixels',...
    'Position',[150 75 35 35],...
    'Tag','objstruct_addlayer_pshbttn',... %[215 90 35 35] side position
    'FontSize',20.0,...
    'FontWeight','bold');

objstruct_remlayer_pshbttn = uicontrol(...
    'Parent',objstruct_layer_pnl,...
    'Style','pushbutton',...
    'String','-',...
    'Units','pixels',...
    'Position',[215 50 35 35],...
    'Tag','objstruct_remlayer_pshbttn',...
    'FontSize',20,...
    'FontWeight','bold',...
    'Visible','Off');

objstruct_crteobjstruct_pshbttn = uicontrol(...
    'Parent',objstruct_layer_pnl,...
    'Style','pushbutton',...
    'String','Create Object',...
    'Units','pixels',...
    'Position',[55 5 150 30],...
    'Tag','objstruct_crteobjstruct_pshbttn',...
    'FontSize',10,...
    'Visible','Off');

objstruct_scroll_slider = uicontrol(...
    'Parent',objstruct_figure,...
    'Style','slider',...
    'Units','pixels',...
    'Position',[255 0 15 170],...
    'Tag','objstruct_scroll_slider',...
    'Visible','On');

%This callback creates component figure when components button is clicked
function comp_button_Callback(hObject, eventdata, handles)
global comp_fig_limit %Introduces limit which limits window to open once
if comp_fig_limit == 0 %If its not opened
    comp_fig_limit = 1; %sets limit to 1 which stops creation of figure
    
    global comp_figure...
    comp_cmp_list comp_help_txt...
    comp_crte_pshbttn...
    comp_mixprop_pnl...
    comp_mixprop_sswel_txt comp_mixprop_sswel_edit...
    comp_mixprop_lswel_txt comp_mixprop_lswel_edit...
    comp_mixprop_gswel_txt comp_mixprop_gswel_edit...
    comp_mixprop_paracond_txt comp_mixprop_paracond_edit...
    comp_mixprop_paratrans_txt comp_mixprop_paratrans_edit...
    comp_mixprop_defvals_txt...
    comp_reset_pshbttn...
    comp_help_pshbttn...
    cmp_name cmp_list cmp_list_orig
    
search_cmp = dir('*.cmp');
for ii = 1:length(search_cmp)
   [pathstr,name,ext]=fileparts(search_cmp(ii).name);
   cmp_name{ii}=name;
   fdd = fopen(search_cmp(ii).name);
   cmp_list{ii} = textscan(fdd,'%s','Delimiter',':');
   cmp_list_orig{ii} = textscan(fdd,'%s','Delimiter','');
end

    %Creates Components figure sets it to cond_figure
    comp_figure = figure(...
        'Position',[520 460 440 270],...
        'Resize','Off',...
        'MenuBar','none',...
        'Name','Components',...
        'tag','comp_fig',...
        'NumberTitle','off',...
        'CloseRequestFcn',@closereq);
    
    %Creates the list with the components
    comp_cmp_list = uicontrol(...
        'Position',[50 70 150 170],...
        'Style','listbox',...
        'String',cmp_name,...
        'Tag','comp_cmp_list',...
        'max',30,...
        'min',1);
    
    %Creates the text of intructions
    comp_help_txt = uicontrol(...
        'Position',[20 30 200 40],...
        'Style','text',...
        'String','HELP TEXT FILLER',...
        'Tag','comp_help_txt');
 
    %Creates the Mixture Properties panel
    comp_mixprop_pnl = uipanel(...
        'Title','Mixture Properties',...
        'Units','pixels',...
        'Position',[240 80 200 160],...
        'FontWeight','bold',...
        'TitlePosition','centertop',...
        'BorderType','none');
   
    %Creates the text of Solid Swelling and edit text box inside the Mixture
    %Properties panel
    comp_mixprop_sswel_txt = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[0 120 70 15],...
        'Style','text',...
        'String','Solid Swelling',...
        'Tag','comp_mixprop_sswel_txt');
    comp_mixprop_sswel_edit = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[105 118 53 22],...
        'Style','edit',...
        'String','0',...
        'Tag','comp_mixprop_sswel_edit',...
        'TooltipString','Default');
    
    %Creates the text of Liquid Swelling and edit text box inside the Mixture
    %Properties panel
    comp_mixprop_lswel_txt = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[0 95 75 15],...
        'Style','text',...
        'String','Liquid Swelling',...
        'Tag','comp_mixprop_lswel_txt');
    comp_mixprop_lswel_edit = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[105 93 53 22],...
        'Style','edit',...
        'String','0',...
        'Tag','comp_mixprop_lswel_edit',...
        'TooltipString','Default');
    
    %Creates the text of Gas Swelling Limit and edit text box inside the
    %Mixutre Properties panel
    comp_mixprop_gswel_txt = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[0 70 90 15],...
        'Style','text',...
        'String','Gas Swelling Limit',...
        'Tag','comp_mixprop_gswel_txt');
    comp_mixprop_gswel_edit = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[105 68 53 22],...
        'Style','edit',...
        'String','1e-30',...
        'Tag','comp_mixprop_gswel_edit',...
        'TooltipString','Default');
    
    %Creates the text of Parallel Conductivity and edit text box inside the
    %Mixture Properties panel
    comp_mixprop_paracond_txt = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[0 45 100 15],...
        'Style','text',...
        'String','Parallel Conductivity',...
        'Tag','comp_mixprop_paracond_txt');
    comp_mixprop_paracond_edit = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[105 43 53 22],...
        'Style','edit',...
        'String','0.5',...
        'Tag','comp_mixprop_paracond_edit',...
        'TooltipString','Default');
    
    %Creates the text of Parallel Transport and edit text box inside the
    %Mixture Properties panel
    comp_mixprop_paratrans_txt = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[0 20 90 15],...
        'Style','text',...
        'String','Parallel Transport',...
        'Tag','comp_mixprop_paratrans_txt');
    comp_mixprop_paratrans_edit = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[105 18 53 22],...
        'Style','edit',...
        'String','0.5',...
        'Tag','comp_mixprop_gparatrans_edit',...
        'TooltipString','Default');
    
    %Creates the text of "Default Value" to indicate default Mixture Properties
    comp_mixprop_defvals_txt = uicontrol(...
        'Parent',comp_mixprop_pnl,...
        'Position',[40 0 90 15],...
        'Style','text',...
        'String','(Default Values)',...
        'Tag','comp_mixprop_defvals_txt',...
        'TooltipString','Default');    
    
    %Creates the create button to create the components file   
    comp_crte_pshbttn = uicontrol(...
        'Position',[140 10 160 30],...
        'Style','pushbutton',...
        'String','Create Components Files',...
        'Tag','comp_crte_pshbttn',...
        'Callback',@comp_crte_pshbttn_callback,...
        'TooltipString','Default');
    
    %Creates the reset button to reset all settings in the Components figure
    comp_reset_pshbttn = uicontrol(...
        'Position',[5 10 35 15],...
        'Style','pushbutton',...
        'String','reset',...
        'Tag','comp_crte_pshbttn',...
        'TooltipString','Default');
    
    comp_help_pshbttn = uicontrol(...
        'Position',[400 10 35 15],...
        'Style','pushbutton',...
        'String','Help',...
        'Tag','comp_help_pshbttn',...
        'TooltipString','Default');
    
elseif comp_fig_limit == 1 %If it is opened
    comp_figure = findobj('Tag','comp_fig'); %set figure 'comp_fig' to comp_figure
    comp_figure.Visible = 'On'; %makes figure visible
    drawnow;
end

function comp_crte_pshbttn_callback(hObject, eventdata, handles)
    global comp_figure...
    comp_cmp_list comp_help_txt...
    comp_crte_pshbttn...
    comp_mixprop_pnl...
    comp_mixprop_sswel_txt comp_mixprop_sswel_edit...
    comp_mixprop_lswel_txt comp_mixprop_lswel_edit...
    comp_mixprop_gswel_txt comp_mixprop_gswel_edit...
    comp_mixprop_paracond_txt comp_mixprop_paracond_edit...
    comp_mixprop_paratrans_txt comp_mixprop_paratrans_edit...
    comp_mixprop_defvals_txt...
    comp_reset_pshbttn...
    comp_help_pshbttn...
    cmp_name cmp_list cmp_list_orig

mix_prop{1} = 'MIXTURES';
mix_prop{2} = sprintf('S SWELLING:           %s',comp_mixprop_sswel_edit.String);
mix_prop{3} = sprintf('L SWELLING:           %s',comp_mixprop_lswel_edit.String);
mix_prop{4} = sprintf('G SWELLING LIMIT:     %s',comp_mixprop_gswel_edit.String);
mix_prop{5} = sprintf('PARALL CONDUCTIVITY:  %s',comp_mixprop_paracond_edit.String);
mix_prop{6} = sprintf('PARALL TRANSPORT:     %s',comp_mixprop_paratrans_edit.String);



%This callback creates output figure when output button is clicked
function out_button_Callback(hObject, eventdata, handles)
global out_fig_limit %Introduces limit which limits window to open once
if out_fig_limit == 0 %If its not opened
    out_figure = figure(...
        'Position',[520 460 440 300],...
        'Resize','Off',... %Creates Output figure sets it to cond_figure
        'MenuBar','none',...
        'Name','Output',...
        'tag','out_fig',...
        'CloseRequestFcn',@closereq);
    out_fig_limit = 1; %sets limit to 1 which stops creation of figure
elseif out_fig_limit == 1 %If it is opened
    out_figure = findobj('Tag','comp_fig'); %set figure 'out_fig' to out_figure
    out_figure.Visible = 'On'; %makes figure visible
    drawnow;
end


function tk2d_button_Callback(hObject, eventdata, handles)

function closereq(src,callbackdata)
global cond_fig_limit comp_fig_limit out_fig_limit
fig_limit = [comp_fig_limit cond_fig_limit out_fig_limit];
idx = find(fig_limit==src);
% Close request function
% to display a question dialog box
selection = questdlg('Do you want to save?',...
    'Close Request Function',...
    'Yes','No','Yes');
switch selection,
    case 'Yes',
        %saves file
    case 'No'
        delete(gcf) %close figure without save
        fig_limit(idx)= 0; %reset limit to 0
        return
end

